[package]
name = "misp-types"
version = "0.1.0"
edition = "2021"
description = "Type definitions for MISP (Malware Information Sharing Platform) API"
license = "MIT"

[dependencies]
serde.workspace = true
serde_json.workspace = true
